2018-07-22 11:50:34,096 ERROR: Exception on /index [GET] [in /Users/imac/anaconda/envs/flask-app/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Users/imac/anaconda/envs/flask-app/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/imac/anaconda/envs/flask-app/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/imac/anaconda/envs/flask-app/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/imac/anaconda/envs/flask-app/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/imac/anaconda/envs/flask-app/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/imac/anaconda/envs/flask-app/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/imac/anaconda/envs/flask-app/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/imac/Dropbox/Python/Flask-app/microblog/app/routes.py", line 32, in index
    next_url=next_url, prev_url=prev_url)
  File "/Users/imac/anaconda/envs/flask-app/lib/python3.6/site-packages/flask/templating.py", line 133, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/imac/anaconda/envs/flask-app/lib/python3.6/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/imac/anaconda/envs/flask-app/lib/python3.6/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/imac/anaconda/envs/flask-app/lib/python3.6/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/imac/anaconda/envs/flask-app/lib/python3.6/site-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/Users/imac/anaconda/envs/flask-app/lib/python3.6/site-packages/jinja2/environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/Users/imac/anaconda/envs/flask-app/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/imac/anaconda/envs/flask-app/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/imac/Dropbox/Python/Flask-app/microblog/app/templates/index.html", line 21, in template
    <a href="{{ next_url or '#' }}">
  File "/Users/imac/anaconda/envs/flask-app/lib/python3.6/site-packages/jinja2/environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "/Users/imac/anaconda/envs/flask-app/lib/python3.6/site-packages/jinja2/parser.py", line 901, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "/Users/imac/anaconda/envs/flask-app/lib/python3.6/site-packages/jinja2/parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "/Users/imac/anaconda/envs/flask-app/lib/python3.6/site-packages/jinja2/parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "/Users/imac/anaconda/envs/flask-app/lib/python3.6/site-packages/jinja2/parser.py", line 268, in parse_block
    node.body = self.parse_statements(('name:endblock',), drop_needle=True)
  File "/Users/imac/anaconda/envs/flask-app/lib/python3.6/site-packages/jinja2/parser.py", line 170, in parse_statements
    self.fail_eof(end_tokens)
  File "/Users/imac/anaconda/envs/flask-app/lib/python3.6/site-packages/jinja2/parser.py", line 104, in fail_eof
    return self._fail_ut_eof(None, stack, lineno)
  File "/Users/imac/anaconda/envs/flask-app/lib/python3.6/site-packages/jinja2/parser.py", line 90, in _fail_ut_eof
    self.fail(' '.join(message), lineno)
  File "/Users/imac/anaconda/envs/flask-app/lib/python3.6/site-packages/jinja2/parser.py", line 59, in fail
    raise exc(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: Unexpected end of template. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2018-07-22 11:50:36,320 ERROR: Exception on /index [GET] [in /Users/imac/anaconda/envs/flask-app/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Users/imac/anaconda/envs/flask-app/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/imac/anaconda/envs/flask-app/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/imac/anaconda/envs/flask-app/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/imac/anaconda/envs/flask-app/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/imac/anaconda/envs/flask-app/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/imac/anaconda/envs/flask-app/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/imac/anaconda/envs/flask-app/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/imac/Dropbox/Python/Flask-app/microblog/app/routes.py", line 32, in index
    next_url=next_url, prev_url=prev_url)
  File "/Users/imac/anaconda/envs/flask-app/lib/python3.6/site-packages/flask/templating.py", line 133, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/imac/anaconda/envs/flask-app/lib/python3.6/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/imac/anaconda/envs/flask-app/lib/python3.6/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/imac/anaconda/envs/flask-app/lib/python3.6/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/imac/anaconda/envs/flask-app/lib/python3.6/site-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/Users/imac/anaconda/envs/flask-app/lib/python3.6/site-packages/jinja2/environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/Users/imac/anaconda/envs/flask-app/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/imac/anaconda/envs/flask-app/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/imac/Dropbox/Python/Flask-app/microblog/app/templates/index.html", line 21, in template
    <a href="{{ next_url or '#' }}">
  File "/Users/imac/anaconda/envs/flask-app/lib/python3.6/site-packages/jinja2/environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "/Users/imac/anaconda/envs/flask-app/lib/python3.6/site-packages/jinja2/parser.py", line 901, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "/Users/imac/anaconda/envs/flask-app/lib/python3.6/site-packages/jinja2/parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "/Users/imac/anaconda/envs/flask-app/lib/python3.6/site-packages/jinja2/parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "/Users/imac/anaconda/envs/flask-app/lib/python3.6/site-packages/jinja2/parser.py", line 268, in parse_block
    node.body = self.parse_statements(('name:endblock',), drop_needle=True)
  File "/Users/imac/anaconda/envs/flask-app/lib/python3.6/site-packages/jinja2/parser.py", line 170, in parse_statements
    self.fail_eof(end_tokens)
  File "/Users/imac/anaconda/envs/flask-app/lib/python3.6/site-packages/jinja2/parser.py", line 104, in fail_eof
    return self._fail_ut_eof(None, stack, lineno)
  File "/Users/imac/anaconda/envs/flask-app/lib/python3.6/site-packages/jinja2/parser.py", line 90, in _fail_ut_eof
    self.fail(' '.join(message), lineno)
  File "/Users/imac/anaconda/envs/flask-app/lib/python3.6/site-packages/jinja2/parser.py", line 59, in fail
    raise exc(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: Unexpected end of template. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2018-07-22 11:54:28,674 INFO: Microblog startup [in /Users/imac/Dropbox/Python/Flask-app/microblog/app/__init__.py:49]
2018-07-22 12:11:37,821 INFO: Microblog startup [in /Users/imac/Dropbox/Python/Flask-app/microblog/app/__init__.py:49]
2018-07-22 12:11:48,133 INFO: Microblog startup [in /Users/imac/Dropbox/Python/Flask-app/microblog/app/__init__.py:49]
2018-07-22 12:12:34,660 INFO: Microblog startup [in /Users/imac/Dropbox/Python/Flask-app/microblog/app/__init__.py:49]
